// gen_pea_examples — Regenerate signed example files for Ciel PEA / 1.0.
//
// USAGE
//   cargo run --package ciel-signer --example gen_pea_examples
//
// WHAT IT DOES
//   1. Derives an Ed25519 test keypair from a hardcoded, publicly-documented
//      32-byte ASCII seed (see TEST_SECRET_SEED below).
//   2. Writes spec/examples/{approve,warn,block,timeout}.json with:
//        - The canonical attestation field values for each verdict class
//        - The test keypair's public key in the `signer` field
//        - A valid Ed25519 signature over the 132-byte Borsh wire encoding
//        - wire.borsh_b64 populated with the base64 of those 132 wire bytes
//   3. Rewrites spec/test-public-key.txt with the real test public key.
//
// IMPORTANT
//   The test secret seed is PUBLIC. The keypair is intentionally committed to
//   the repository so anyone can reproduce the example signatures. DO NOT USE
//   THIS KEYPAIR FOR ANYTHING OTHER THAN SPEC EXAMPLE SIGNATURES. Production
//   issuers MUST generate independent keys.
//
// NOTE ON `block.json` vs the pinned fixture
//   The pinned binary fixture `crates/ciel-signer/fixtures/ciel_attestation_v1.bin`
//   uses a placeholder `signer` value (0x41..0x60) for which no private key
//   exists. That fixture demonstrates *wire format*. The example `block.json`
//   generated by this binary uses the test keypair's real public key so the
//   signature verifies end-to-end. The attestation field values are otherwise
//   identical to the pinned fixture.

use ciel_signer::attestation::{CIEL_ATTESTATION_MAGIC, Verdict, ATTESTATION_VERSION, TIMEOUT_SENTINEL, EXPIRY_SLOTS};
use ciel_signer::pea::{to_pea_json, PeaFlag, PeaFlagSeverity, PeaIntent, PEA_SPEC_VERSION};
use ciel_signer::CielAttestation;
use ed25519_dalek::{Signer, SigningKey};
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

/// Public, documented seed used to derive the spec test keypair.
/// 32 ASCII bytes. Intentionally published; see file-header warning.
const TEST_SECRET_SEED: [u8; 32] = *b"CIEL-PEA-TEST-KEY-V1-DONOTUSE-AB";

/// Canonical example recipe. One per verdict class.
struct Example {
    name: &'static str,
    verdict: Verdict,
    tx_hash: [u8; 32],
    safety_score: u16,
    optimality_score: u16,
    checker_outputs_hash: [u8; 32],
    slot: u64,
    timestamp: i64,
    timeout_at_ms: u16,
    flags: Vec<PeaFlag>,
    intent: Option<PeaIntent>,
    description: &'static str,
}

fn bytes32_from_pattern(start: u8) -> [u8; 32] {
    let mut out = [0u8; 32];
    for (i, b) in out.iter_mut().enumerate() {
        *b = start.wrapping_add(i as u8);
    }
    out
}

fn bytes32_seq_a001() -> [u8; 32] {
    // a001a002..a010 pattern (as used in approve.json)
    let mut out = [0u8; 32];
    for i in 0..16 {
        out[i * 2] = 0xa0;
        out[i * 2 + 1] = 0x01 + i as u8;
    }
    out
}

fn bytes32_seq_b001() -> [u8; 32] {
    let mut out = [0u8; 32];
    for i in 0..16 {
        out[i * 2] = 0xb0;
        out[i * 2 + 1] = 0x01 + i as u8;
    }
    out
}

fn bytes32_seq_c001() -> [u8; 32] {
    let mut out = [0u8; 32];
    for i in 0..16 {
        out[i * 2] = 0xc0;
        out[i * 2 + 1] = 0x01 + i as u8;
    }
    out
}

fn bytes32_seq_d001() -> [u8; 32] {
    let mut out = [0u8; 32];
    for i in 0..16 {
        out[i * 2] = 0xd0;
        out[i * 2 + 1] = 0x01 + i as u8;
    }
    out
}

fn bytes32_seq_e001() -> [u8; 32] {
    let mut out = [0u8; 32];
    for i in 0..16 {
        out[i * 2] = 0xe0;
        out[i * 2 + 1] = 0x01 + i as u8;
    }
    out
}

fn bytes32_ee_ab_repeat() -> [u8; 32] {
    // eeeeeeee 0123456789 eeeeeeee 0123456789 eeeeeeee 0123456789 eeeeeeee 01
    // Matches the intent_fingerprint used in warn.json.
    let hex = "eeeeeeee0123456789eeeeeeee0123456789eeeeeeee0123456789eeeeeeee01";
    let mut out = [0u8; 32];
    for (i, b) in out.iter_mut().enumerate() {
        let byte = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
        *b = byte;
    }
    out
}

fn bytes32_block_intent_fingerprint() -> [u8; 32] {
    // Matches block.json's intent_fingerprint: abcdef0123456789... repeated
    let hex = "abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789";
    let mut out = [0u8; 32];
    for (i, b) in out.iter_mut().enumerate() {
        let byte = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
        *b = byte;
    }
    out
}

fn hex_from(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{:02x}", b));
    }
    s
}

fn canonical_examples() -> Vec<Example> {
    vec![
        // APPROVE — normal happy path
        Example {
            name: "approve",
            verdict: Verdict::Approve,
            tx_hash: bytes32_seq_a001(),
            safety_score: 9500,
            optimality_score: 8200,
            checker_outputs_hash: bytes32_seq_b001(),
            slot: 350_000_100,
            timestamp: 1_712_000_100,
            timeout_at_ms: 0,
            flags: vec![],
            intent: None,
            description: "Example APPROVE verdict. Values are illustrative. \
                          Regenerated by cargo run --example gen_pea_examples.",
        },
        // WARN — intent satisfied but with notable caveats
        Example {
            name: "warn",
            verdict: Verdict::Warn,
            tx_hash: bytes32_seq_c001(),
            safety_score: 6800,
            optimality_score: 5500,
            checker_outputs_hash: bytes32_seq_d001(),
            slot: 350_000_200,
            timestamp: 1_712_000_200,
            timeout_at_ms: 0,
            flags: vec![
                PeaFlag {
                    code: "ORACLE_DEVIATION".into(),
                    severity: PeaFlagSeverity::Warn,
                    detail: Some(
                        "Switchboard vs Pyth spread 8.2% — elevated but within acceptance band"
                            .into(),
                    ),
                },
                PeaFlag {
                    code: "MEV_SANDWICH_RISK".into(),
                    severity: PeaFlagSeverity::Warn,
                    detail: Some("Slippage tolerance high for route size".into()),
                },
            ],
            intent: Some(PeaIntent {
                intent_nl: Some("swap 10000 USDC for SOL".into()),
                intent_fingerprint: Some(hex_from(&bytes32_ee_ab_repeat())),
                intent_satisfied: Some(true),
            }),
            description: "Example WARN verdict. Transaction allowed but carries a notable caveat. \
                          Regenerated by cargo run --example gen_pea_examples.",
        },
        // BLOCK — Drift-style exploit stopped; field values mirror the pinned fixture
        // EXCEPT for the signer, which is replaced with the test keypair public key so
        // the signature verifies end-to-end.
        Example {
            name: "block",
            verdict: Verdict::Block,
            tx_hash: bytes32_from_pattern(0x01),
            safety_score: 3500,
            optimality_score: 0,
            checker_outputs_hash: bytes32_from_pattern(0x21),
            slot: 350_000_000,
            timestamp: 1_712_000_000,
            timeout_at_ms: 0,
            flags: vec![
                PeaFlag {
                    code: "ORACLE_DEVIATION".into(),
                    severity: PeaFlagSeverity::Block,
                    detail: Some(
                        "Switchboard vs Pyth spread 42.3% — oracle manipulation suspected".into(),
                    ),
                },
                PeaFlag {
                    code: "AUTHORITY_HIJACK".into(),
                    severity: PeaFlagSeverity::Block,
                    detail: Some("Hidden SetAuthority instruction in CPI depth 3".into()),
                },
            ],
            intent: Some(PeaIntent {
                intent_nl: Some("deposit CVT collateral and borrow SOL".into()),
                intent_fingerprint: Some(hex_from(&bytes32_block_intent_fingerprint())),
                intent_satisfied: Some(false),
            }),
            description: "Canonical BLOCK example. Attestation field values match the pinned \
                          fixture ciel_attestation_v1.bin EXCEPT the `signer` field, which is \
                          the spec test public key so the signature verifies end-to-end. \
                          See test-public-key.txt. The pinned fixture demonstrates wire format; \
                          this example demonstrates end-to-end signature verification.",
        },
        // TIMEOUT — infrastructure deadline exceeded; sentinel scores 0xFFFF
        Example {
            name: "timeout",
            verdict: Verdict::Timeout,
            tx_hash: bytes32_seq_e001(),
            safety_score: TIMEOUT_SENTINEL,
            optimality_score: TIMEOUT_SENTINEL,
            checker_outputs_hash: [0u8; 32],
            slot: 350_000_300,
            timestamp: 1_712_000_300,
            timeout_at_ms: 80,
            flags: vec![PeaFlag {
                code: "INFRA_DEADLINE_EXCEEDED".into(),
                severity: PeaFlagSeverity::Info,
                detail: Some(
                    "Evaluator did not complete within 80ms budget; no verdict-affecting \
                     output produced"
                        .into(),
                ),
            }],
            intent: None,
            description: "Example TIMEOUT verdict. MUST NOT be treated as APPROVE or WARN. \
                          MUST NOT be overridden. The caller SHOULD retry with a fresh \
                          submission. Regenerated by cargo run --example gen_pea_examples.",
        },
    ]
}

/// Find the spec/examples directory relative to CARGO_MANIFEST_DIR.
/// CARGO_MANIFEST_DIR = .../ciel/crates/ciel-signer, so spec/ is ../../spec.
fn spec_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("spec")
}

fn main() -> Result<(), Box<dyn Error>> {
    // Derive the test keypair deterministically.
    let signing_key = SigningKey::from_bytes(&TEST_SECRET_SEED);
    let verifying_key = signing_key.verifying_key();
    let pubkey_bytes: [u8; 32] = verifying_key.to_bytes();
    let pubkey_hex = hex_from(&pubkey_bytes);

    println!("Ciel PEA / 1.0 — spec example generator");
    println!("========================================");
    println!("Test public key: {}", pubkey_hex);
    println!();

    let examples_dir = spec_dir().join("examples");
    fs::create_dir_all(&examples_dir)?;

    let mut written_paths: Vec<PathBuf> = Vec::new();

    for ex in canonical_examples() {
        // Build the attestation with the real signer pubkey. new() sets
        // magic, version, and expiry_slot = slot + EXPIRY_SLOTS.
        let att = if ex.verdict == Verdict::Timeout {
            // new_timeout() enforces the sentinel scores. We pass the same
            // timeout_at_ms the example expects.
            CielAttestation::new_timeout(
                ex.tx_hash,
                ex.checker_outputs_hash,
                ex.slot,
                pubkey_bytes,
                ex.timestamp,
                ex.timeout_at_ms,
            )
        } else {
            CielAttestation::new(
                ex.tx_hash,
                ex.verdict,
                ex.safety_score,
                ex.optimality_score,
                ex.checker_outputs_hash,
                ex.slot,
                pubkey_bytes,
                ex.timestamp,
                ex.timeout_at_ms,
            )
        };

        // Sanity: magic + version + expiry are derived correctly.
        debug_assert_eq!(att.magic, CIEL_ATTESTATION_MAGIC);
        debug_assert_eq!(att.version, ATTESTATION_VERSION);
        debug_assert_eq!(att.expiry_slot, ex.slot + EXPIRY_SLOTS);

        // Borsh-serialize and sign.
        let wire_bytes = borsh::to_vec(&att)?;
        debug_assert_eq!(wire_bytes.len(), 132, "wire length must be 132");
        let signature = signing_key.sign(&wire_bytes);
        let signature_bytes: [u8; 64] = signature.to_bytes();

        // Build the envelope via the canonical helper.
        let mut envelope =
            to_pea_json(&att, &signature_bytes, &ex.flags, ex.intent.as_ref())?;

        // Attach the per-example description. serde_json::Map is a BTreeMap,
        // so `_description` naturally sorts to the top of the file (underscore
        // precedes letters lexicographically).
        if let Some(map) = envelope.as_object_mut() {
            map.insert(
                "_description".into(),
                serde_json::Value::String(ex.description.to_string()),
            );
        }

        // Pretty-print and write.
        let path = examples_dir.join(format!("{}.json", ex.name));
        fs::write(&path, serde_json::to_string_pretty(&envelope)? + "\n")?;
        println!("wrote {}", path.display());
        written_paths.push(path);
    }

    // Rewrite spec/test-public-key.txt so it always matches the key this
    // binary derives. Keeps the published spec in lockstep with the committed
    // seed and the signed examples.
    let pubkey_txt_path = spec_dir().join("test-public-key.txt");
    let pubkey_txt = format!(
        "Ciel PEA / 1.0 — Test Public Key\n\
         =================================\n\
         \n\
         This Ed25519 public key is used to sign the four example files under\n\
         ./examples/. It is published here so that anyone can verify the example\n\
         signatures without coordinating with the Ciel project.\n\
         \n\
         The key is derived deterministically from the 32-byte ASCII seed defined\n\
         in crates/ciel-signer/examples/gen_pea_examples.rs. The seed is public\n\
         and intentionally committed. Any attacker can trivially impersonate\n\
         signatures under this key. Production issuers MUST derive fresh keys\n\
         and publish their public keys independently.\n\
         \n\
         Public key (32 bytes, hex, lowercase):\n\
         \n\
             {pubkey_hex}\n\
         \n\
         To regenerate example signatures against this key:\n\
         \n\
             cargo run --package ciel-signer --example gen_pea_examples\n\
         \n\
         The binary overwrites spec/examples/*.json and this file with the current\n\
         pubkey derived from the source-committed seed.\n\
         \n\
         DO NOT USE THIS KEYPAIR FOR ANYTHING OTHER THAN REGENERATING SPEC EXAMPLES.\n"
    );
    fs::write(&pubkey_txt_path, pubkey_txt)?;
    println!("wrote {}", pubkey_txt_path.display());

    // Verify every file we wrote roundtrips through the spec verifier logic.
    println!();
    println!("Self-verification pass:");
    for path in &written_paths {
        verify_file(path, &verifying_key)?;
        println!("  ✓ {} signature verified", path.display());
    }

    println!();
    println!("Done. {} example files written and verified.", written_paths.len());
    Ok(())
}

/// Self-verify: decode the envelope we just wrote and verify the signature
/// against the test pubkey. Fails fast if anything drifts.
fn verify_file(path: &Path, verifying_key: &ed25519_dalek::VerifyingKey) -> Result<(), Box<dyn Error>> {
    use base64::{engine::general_purpose::STANDARD as B64, Engine as _};

    let text = fs::read_to_string(path)?;
    let envelope: serde_json::Value = serde_json::from_str(&text)?;

    // Spec version and fixture version checks.
    let spec_version = envelope
        .get("spec_version")
        .and_then(|v| v.as_str())
        .ok_or("missing spec_version")?;
    assert_eq!(spec_version, PEA_SPEC_VERSION);

    // Decode wire bytes.
    let wire_b64 = envelope
        .get("wire")
        .and_then(|v| v.get("borsh_b64"))
        .and_then(|v| v.as_str())
        .ok_or("missing wire.borsh_b64")?;
    let wire_bytes = B64.decode(wire_b64)?;
    assert_eq!(wire_bytes.len(), 132);

    // Decode signature.
    let sig_hex = envelope
        .get("signature")
        .and_then(|v| v.as_str())
        .ok_or("missing signature")?;
    let mut sig_bytes = [0u8; 64];
    for i in 0..64 {
        sig_bytes[i] = u8::from_str_radix(&sig_hex[i * 2..i * 2 + 2], 16)?;
    }
    let signature = ed25519_dalek::Signature::from_bytes(&sig_bytes);

    // Strict Ed25519 verify.
    verifying_key
        .verify_strict(&wire_bytes, &signature)
        .map_err(|e| format!("signature verification failed: {e}"))?;

    Ok(())
}
